#!/usr/bin/env bash

# Monitors is set in displays

#
#bspc monitor "${primaryMonitor}" -d 1 2 3 4 5 6 7 8 9 0

# Padding is set in panel
#bspc config top_padding 20

~/.config/bspwm/pre_startup

bspc config border_width            2
bspc config window_gap              12

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_by_distance       true
bspc config history_aware_focus     true

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

~/.config/bspwm/rules

primaryDisplay=$(~/.config/bspwm/displays 'once')
#bspc monitor "${primaryDisplay}" --reset-desktops 1 2 3 4 5 6 7 8 9 0
bspc monitor "${primaryDisplay}" --reset-desktops          

~/.config/bspwm/post_startup &