#!/usr/bin/env bash

scriptDir=$(dirname `realpath -P "$0"`)
imageDir=${1:-$HOME/pictures/wallpapers/}
num=0

# Kill dunst so we don't see the notifications on screenshots
#kill $(pgrep -f dunst) 2>&1 >/dev/null

for fName in "${imageDir}"*; do
  if [[ -f "${fName}" ]]; then
    num=$((${num} +1))
    "${scriptDir}/change_theme" "${fName}"
    sleep 1.0s
    ~/.config/bash/scripts/scrot
  fi
done

# Restart dunst
#dunst &

notify-send -u 'low' "Took ${num} screenshots!"